"""Remove unused variables, make location and caption not required

Revision ID: 0f6807535994
Revises: ada3d0acbcea
Create Date: 2020-06-14 12:46:38.321269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f6807535994'
down_revision = 'ada3d0acbcea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image') as batch_op:
        batch_op.alter_column('caption',
                   existing_type=sa.VARCHAR(length=250),
                   nullable=True)
        batch_op.alter_column('location',
                   existing_type=sa.VARCHAR(length=250),
                   nullable=True)
        batch_op.drop_column('thumbnail_basename')
        batch_op.drop_column('downsampled_path')
        batch_op.drop_column('downsampled_size_string')
        batch_op.drop_column('thumbnail_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image') as batch_op:
        batch_op.add_column(sa.Column('thumbnail_path', sa.VARCHAR(length=250), nullable=True))
        batch_op.add_column(sa.Column('downsampled_size_string', sa.VARCHAR(length=250), nullable=True))
        batch_op.add_column(sa.Column('downsampled_path', sa.VARCHAR(length=250), nullable=True))
        batch_op.add_column(sa.Column('thumbnail_basename', sa.VARCHAR(length=250), nullable=True))
        batch_op.alter_column('location',
                   existing_type=sa.VARCHAR(length=250),
                   nullable=False)
        batch_op.alter_column('caption',
                   existing_type=sa.VARCHAR(length=250),
                   nullable=False)
    # ### end Alembic commands ###
