"""Add dimensions to derived images

Revision ID: ada3d0acbcea
Revises: 154512454d6d
Create Date: 2020-06-13 19:12:05.942582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ada3d0acbcea'
down_revision = '154512454d6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('downsampled_image', sa.Column('dimensions', sa.String(length=25), nullable=True))
    op.add_column('thumbnail_image', sa.Column('dimensions', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thumbnail_image', 'dimensions')
    op.drop_column('downsampled_image', 'dimensions')
    # ### end Alembic commands ###
